@extends('layouts.app')
@section('title', 'Reports')
@section('page-title', 'Reports')
@section('page-description', 'Generate and manage farm reports')

@section('content')
<div class="report-grid" style="margin-bottom:24px">
    @foreach($reportTypes as $report)
    <div class="report-card">
        <div class="icon-circle"><i class="bi bi-{{ $report['icon'] }}"></i></div>
        <h4>{{ $report['name'] }}</h4>
        <p>{{ $report['category'] }} report with detailed analytics</p>
        <form method="POST" action="{{ route('reports.generate') }}">
            @csrf
            <input type="hidden" name="report_name" value="{{ $report['name'] }}">
            <input type="hidden" name="category" value="{{ $report['category'] }}">
            <button type="submit" class="btn btn-primary btn-sm">Generate</button>
        </form>
    </div>
    @endforeach
</div>

<div class="grid-2">
    <div class="card">
        <div class="card-header"><h3>Recent Generated Reports</h3></div>
        <div class="card-body" style="padding:0">
            <table class="data-table">
                <thead><tr><th>Report Name</th><th>Category</th><th>Date Generated</th><th>Generated By</th></tr></thead>
                <tbody>
                    @forelse($reports as $report)
                    <tr>
                        <td><strong>{{ $report->report_name }}</strong></td>
                        <td>{{ $report->category }}</td>
                        <td>{{ $report->generated_at->format('M d, Y') }}</td>
                        <td>{{ $report->generator->name }}</td>
                    </tr>
                    @empty
                    <tr><td colspan="4" style="text-align:center;color:#6c757d">No reports generated yet</td></tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
    <div class="card">
        <div class="card-header"><h3>Quick Actions</h3></div>
        <div class="card-body">
            <ul class="quick-actions">
                <li><a href="#">Custom Report</a><p>Create custom report with specific parameters</p></li>
                <li><a href="#">Scheduled Report</a><p>Manage automatically generated reports</p></li>
                <li><a href="#">Export All Reports</a><p>Export all reports in various formats</p></li>
                <li><a href="#">Report Settings</a><p>Manage report preferences and configurations</p></li>
            </ul>
        </div>
    </div>
</div>
@endsection
