export default {
    title: 'Egg Production',
    endpoint: '/api/eggs',
    summaryFields: [
        { key: 'eggsToday', label: 'Eggs Today' },
        { key: 'weekTotal', label: 'This Week' },
        { key: 'monthTotal', label: 'This Month' },
    ],
    columns: [
        { key: 'date', label: 'Date' },
        { key: 'building_id', label: 'Building', render: (item) => item.building?.name ?? '' },
        { key: 'total_eggs', label: 'Total Eggs' },
        { key: 'soft_shell_eggs', label: 'Soft Shell Eggs' },
        { key: 'damaged_eggs', label: 'Damaged Eggs' },
        { key: 'cracked_eggs', label: 'Cracked Eggs' },
        { key: 'small_eggs', label: 'Small' },
        { key: 'medium_eggs', label: 'Medium' },
        { key: 'large_eggs', label: 'Large' },
        { key: 'extra_large_eggs', label: 'Extra Large' },
        { key: 'jumbo_eggs', label: 'Jumbo' },
        { key: 'super_jumbo_eggs', label: 'Super Jumbo' },
    ],
    formFields: [
        { key: 'date', label: 'Date', type: 'date' },
        { key: 'building_id', label: 'Building', type: 'select', optionsKey: 'buildings' },
        { key: 'total_eggs', label: 'Total Eggs', type: 'number' },
        { key: 'soft_shell_eggs', label: 'Soft Shell Eggs', type: 'number' },
        { key: 'damaged_eggs', label: 'Damaged Eggs', type: 'number' },
        { key: 'cracked_eggs', label: 'Cracked Eggs', type: 'number' },
        { key: 'small_eggs', label: 'Small Eggs', type: 'number' },
        { key: 'medium_eggs', label: 'Medium Eggs', type: 'number' },
        { key: 'large_eggs', label: 'Large Eggs', type: 'number' },
        { key: 'extra_large_eggs', label: 'Extra Large Eggs', type: 'number' },
        { key: 'jumbo_eggs', label: 'Jumbo Eggs', type: 'number' },
        { key: 'super_jumbo_eggs', label: 'Super Jumbo Eggs', type: 'number' },
    ],
};
